apiVersion: apps/v1
kind: Deployment
metadata:
  name: callme-deployment
spec:
  selector:
    matchLabels:
      app: callme
  template:
    metadata:
      labels:
        app: callme
    spec:
      containers:
        - name: callme
          image: piomin/callme-service

          ports:
            - containerPort: 8080